services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE broadcaster;' -U postgres
notifications: 
  email: false
sudo: false

cache:
  directories:
    - 'node_modules'
before_script:
  - npm install
  
language: node_js
node_js:
  - "12.13.0"

scripts:
  - npm run test
after_success:
  - npm run coveralls